AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'config/boot.rb'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'Rakefile'
  TargetRubyVersion: 2.4.1

Style/Encoding:
  EnforcedStyle: when_needed
  Enabled: true

Metrics/LineLength:
  Max: 120

Layout/SpaceInsideParens:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
