default: &default
  adapter: postgresql
  encoding: unicode
  pool: 15
  username: <%= ENV.fetch('PG_USERNAME') %>
  password: <%= ENV.fetch('PG_PASSWORD') %>
  host: <%= ENV.fetch('PG_HOST') %>
  port: <%= ENV.fetch('PG_PORT') %>

development:
  <<: *default
  database: cryptostatus_development

test:
  <<: *default
  database: cryptostatus_test

production:
  <<: *default
  database: cryptostatus_production
