default: &default
  adapter: postgresql
  encoding: unicode
  pool: 15

development:
  <<: *default
  database: cryptostatus_development

test:
  <<: *default
  database: cryptostatus_test

production:
  <<: *default
  database: cryptostatus_production
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>