currency_logging_worker:
  every: '30s'
  class: CurrencyLoggingWorker
daily_twitter_post_worker:
  every: '12h'
  class: DailyPostWorker
  args: twitter
history_cleanup_worker:
  every: '12h'
  class: HistoryCleanupWorker

